### ISSUE TITLE
Failed to load class "org.slf4j.impl.StaticLoggerBinder".

### ISSUE THREAD

**Issue by dvberkel** [ClojureNauts/clojurenauts-twitter-bot#2]
When I start the application with `lein run` I am greeted with the following message

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

**Comment by mkp7** [comment]
How did you solved the issue?

**Comment by dvberkel** [comment]
Good question. For the life of me, I can't remember. I will do some investigating. Will be back soon

**Comment by dvberkel** [comment]
I couldn't find any relevant commits. Sorry for that

**Comment by mkp7** [comment]
Never mind! I found this so far http://www.bahmanm.com/blogs/how-to-add-logging-to-a-clojure-project. Haven't solved the whole issue but might help someone. Thanks for response!
